# version: "3"
services:
    cantaloupe:
        networks:
        - internal
    iiif_ingest:
        networks:
        - internal
    mirador:
      environment:
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        VIRTUAL_HOST: ${LETSENCRYPT_HOST}
        VIRTUAL_PORT: 80
      networks:
      - internal
      - proxy

    jobs:
      networks:
      - internal

networks:
  internal:
  proxy:
    external:
      name: ${PROXY_NETWORK_NAME}
