FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# copy app code
COPY . /app

EXPOSE 8000

CMD ["uvicorn", "iiif_ingest_service:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]